#!/usr/bin/env node
/**
 * Regenerate the Homebrew formula from what npm actually published.
 *
 * The formula carries three facts that must agree with the registry: the
 * version, the tarball URL, and its sha256. Retyping any of them is how a tap
 * ends up installing a different build than the one it names - and Homebrew
 * will not notice, because the sha256 it checks is the one you typed.
 *
 * So nothing here is typed. The version comes from package.json, the URL and
 * the digest from the registry entry for that exact version, and the digest is
 * computed from the bytes actually downloaded rather than copied from npm's
 * metadata. If npm's `dist.integrity` and the downloaded bytes disagree, that
 * is a supply-chain problem and this exits non-zero instead of writing a file.
 *
 *   node scripts/update_homebrew_formula.mjs [--version X.Y.Z] [--out <path>]
 *
 * Default --out is ../homebrew-tap/Formula/ux-ui-agent-skills.rb, which is
 * where the tap sits when cloned next to this repo. Prints to stdout with
 * --stdout.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const argv = process.argv.slice(2);
const flag = (name) => {
  const i = argv.indexOf(`--${name}`);
  return i === -1 ? null : argv[i + 1];
};

const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
const version = flag('version') || pkg.version;
const out = flag('out') || join(ROOT, '..', 'homebrew-tap', 'Formula', 'ux-ui-agent-skills.rb');
const toStdout = argv.includes('--stdout');

const fail = (msg) => { console.error(`ERROR: ${msg}`); process.exit(1); };

const meta = await fetch(`https://registry.npmjs.org/${pkg.name}/${version}`)
  .then(r => r.ok ? r.json() : fail(`registry has no ${pkg.name}@${version} (HTTP ${r.status}). Publish first.`));

const url = meta.dist.tarball;
const bytes = Buffer.from(await fetch(url).then(r => r.ok ? r.arrayBuffer() : fail(`could not download ${url}`)));
const sha256 = createHash('sha256').update(bytes).digest('hex');

// npm publishes dist.integrity as sha512; check the bytes against it so a
// corrupted or substituted download cannot be hashed into the formula.
if (meta.dist.integrity?.startsWith('sha512-')) {
  const want = meta.dist.integrity.slice('sha512-'.length);
  const got = createHash('sha512').update(bytes).digest('base64');
  if (got !== want) fail(`downloaded tarball does not match npm's integrity for ${version}. Not writing a formula.`);
}

const formula = `# Generated by scripts/update_homebrew_formula.mjs - do not hand-edit the
# version, url or sha256. Regenerate after every npm release instead:
#   node scripts/update_homebrew_formula.mjs
class UxUiAgentSkills < Formula
  desc "Design-system kit for coding agents: tokens, components, WCAG gates"
  homepage "https://github.com/plugin87/ux-ui-agent-skills"
  url "${url}"
  sha256 "${sha256}"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  def caveats
    <<~EOS
      Install the kit into a project:
        cd your-project && ux-ui-skills init

      Pick the agent surface:
        ux-ui-skills init --agent claude   # CLAUDE.md, skills, rules, hooks
        ux-ui-skills init --agent codex    # AGENTS.md (Codex, Cursor, Copilot, Aider)
        ux-ui-skills init --agent both

      The render gates need a browser once per machine:
        npx playwright install chrome
    EOS
  end

  test do
    # The CLI must report the version Homebrew installed. This is the assertion
    # that catches a bottle built from a different tarball than the formula names.
    assert_equal version.to_s, shell_output("#{bin}/ux-ui-skills version").strip

    # init must actually write the surface it promises, and must not write the
    # Claude Code mechanisms on the codex route.
    system bin/"ux-ui-skills", "init", "--agent", "codex"
    assert_path_exists testpath/"AGENTS.md"
    refute_path_exists testpath/"CLAUDE.md"
    refute_path_exists testpath/".claude"

    # The gates are plain Node and Python, so they ship on every route.
    assert_path_exists testpath/"scripts/verify_states.mjs"
    assert_path_exists testpath/"tokens/colors.json"

    # And one browser-free gate must actually run and pass on the kit's own tokens.
    system "python3", testpath/"scripts/validate_tokens.py", testpath/"tokens"
  end
end
`;

if (toStdout) {
  process.stdout.write(formula);
} else {
  if (!existsSync(dirname(out))) mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, formula);
  console.log(`wrote ${out}`);
}
console.log(`version ${version}`);
console.log(`url     ${url}`);
console.log(`sha256  ${sha256}`);
